@startuml

actor User
participant "ExportDataUI" as ui
participant "ExportDataController" as ctrl
participant "CellRange" as range
participant "DatabaseConnection" as db
participant "DatabaseExportOperations" as op

User -> ui : starts the process of exportation to database
User -> ui : inserts the range of cells, the database connection and the table name

create range
ui -> range : create(firstCell, lastCell)

create ctrl
ui -> ctrl : create(range, databaseConnection, driver, tableName)

ui -> ctrl : export()

create db
ctrl -> db : create(databaseConnection, driver)
ctrl -> db : openConnection()

ctrl -> range : numberOfColumns = getNumberOfCollumns()

create op
ctrl -> op  : create()
ctrl -> op : createTable(tableName, numberOfCollumns)
ctrl -> op : fillTable()
ctrl -> db : closeConnection()

@enduml
