@startuml ipc02_2_sd.png

actor User
participant ControllerFindWorkbooks
participant UIFindWorkbooksExtension
participant Directory
participant FindWorkbooksPublisher
participant SearchFiles
participant PreviewWorkbookBuilder
participant UserDefinedFileAttributeView
participant Files
participant PreviewWorkbook

User->UIFindWorkbooksExtension:Insert the root path to find
UIFindWorkbooksExtension-->User: Asks to insert a regular expression
User->UIFindWorkbooksExtension: Enters the regular expression and launches the search
UIFindWorkbooksExtension-->ControllerFindWorkbooks:findPath(String path)
create Directory
ControllerFindWorkbooks->Directory:new()
create SearchFiles
Directory->SearchFiles:create()
Directory -> SearchFiles: isRegexValid(regex))
loop
Directory->SearchFiles: checkIfMatches(expression)
Directory->Directory:Workbook w=searchFile(String pattern)
Directory->FindWorkbooksPublisher:notifyObservers(Object w)
end
User<--UIFindWorkbooksExtension: Displays the search results
User->UIFindWorkbooksExtension: Choose workbook to preview
UIFindWorkbooksExtension->ControllerFindWorkbooks:buildWorkbookPreview(Workbook workbook)
create PreviewWorkbookBuilder
ControllerFindWorkbooks->PreviewWorkbookBuilder:loadPrev()
create File
PreviewWorkbookBuilder->File: new()
create PreviewWorkbook
PreviewWorkbookBuilder->PreviewWorkbook: new()
loop
PreviewWorkbookBuilder->Files: getFilesAttributeView(file.toPath, UserDefinedFileAttribtueView.class)
create UserDefinedFileAttributeView
create ByteBuffer
PreviewWorkbookBuilder->ByteBuffer: allocate(view.size("cell"+i));
PreviewWorkbookBuilder->UserDefinedFileAttributeView: read("cell" + i,bytebuffer);
PreviewWorkbookBuilder->PreviewWorkbook: buildPreviewArea(cell[])
PreviewWorkbookBuilder->PreviewWorkbookPublisher: notifyObservers(previewWorkbook)
end

UIFindWorkbooksExtension-->User: Display preview area filled with first non-empty cells


@enduml
