@startuml ipc02_2_ssd.png

actor User
participant "System" as S
User -> S : Selects "Workbook Search" option
S --> User : Asks to insert a root path to find.
User -> S : Enters the path 
S --> User : Asks to insert a regular expression.
User -> S : Enters the regular expression and launches the search
S --> User : Displays the search results
User -> S : Clicks on workbook to preview
S --> User : Display preview area filled with first non-empty cells
@enduml