@startuml

skinparam handwritten true
skinparam monochrome true
skinparam defaultFontName FG Virgil
skinparam shadowing false

class CommClientWorker
class ClientHandler
class DataTransferObject
class ServerHandler
class CommServer
class CommServerWorker

CommClientWorker "1" - "*" ClientHandler : uses >
ClientHandler "1" -- "1" DataTransferObject : sends >
DataTransferObject "1" -- "1" ClientHandler : are received by >
DataTransferObject "1" -- "1" ServerHandler : are received by >
ServerHandler "1" -- "1" DataTransferObject : sends >
ServerHandler "*" - "1" CommServerWorker : uses <
CommServerWorker "*" - "1" CommServer : creates <

@enduml
