@startuml
class MacroExtensionUI
class BeanShellLoaderController
class BeanShellLoader
class BeanShellClassInstance
MacroExtensionUI --> BeanShellLoaderController
BeanShellLoaderController ->BeanShellLoader
BeanShellLoaderController ..> BeanShellClassInstance 
@enduml
