@startuml design_default_script.png
actor User
User -> MacroExtensionUI : Selects beanshell script option
MacroExtensionUI -> BeanShellClassLoaderController : createClassFromScript(aScript,uiController)
BeanShellClassLoaderController -> BeanShellClassLoader :create(aScript,uiController) --- this is the default script
 BeanShellClassLoader -> BeanShellClassLoaderController : return new BeanShellClassInstance()
BeanShellClassLoaderController -> BeanShellClassInstance : beanShellResult = executeScript()
 BeanShellClassInstance ->  BeanShellClassInstance : new Workbook();
BeanShellClassInstance ->  BeanShellClassInstance : new Macro(expression);
BeanShellClassInstance -> MacroController : executeMacro(macro);
BeanShellClassInstance -> BeanShellClassLoaderController : return new BeanShellResult()
BeanShellClassLoaderController ->MacroExtensionUI : return beanShellResult
MacroExtensionUI -> User : shows result
@enduml
