@startuml core02_01_design3.png
    participant "uic: UIController" as uic
    participant "uiExtension : UIExtensionComments" as UIExt
    participant "User" as u
    participant "Cell" as cell
    participant "CommentPanel : JPanel" as cp
    participant "CommentController" as ctrl
    participant "commentField: JTextArea" as commentField
    participant "applyAction: ApplyAction" as applyAction
    
    create ctrl
    UIExt -> ctrl : create()

    note right #aqua
        This is a refactor of 
        the diagram of the 
        previous use case (Core02.1)
    end note

    create cp
    UIExt -> cp :  create(uic) 

    cp -> uic : addSelectionListener(this)
    
    create commentField
    cp -> commentField: new()

    create applyAction
    cp -> applyAction : new()

    note right of applyAction
        ApplyAction is a innerclass 
        of CommentPanel.
        As such, it can access the 
        members of CommentPanel,
        for instance, the
        current cell.
    end note

    cp -> commentField : addFocusListener(applyAction)

    == meanwhile a cell is selected...the user enters text in "commentField" and the textbox loses the focus ==

    alt user changes a comment
        commentField -> applyAction : focusLost(FocusEvent e)
        activate applyAction
        applyAction -> commentField : newComment=getText()
        applyAction -> ctrl : changeComment(cell, oldComment, newComment)
        deactivate applyAction

        activate ctrl
        ctrl -> cell : changeUserComment(oldComment, newComment, currentUser)
        ctrl -> uic : setWorkbookModified(...)
        deactivate ctrl
    else user adds a comment
        commentField -> applyAction : focusLost(FocusEvent e)
        activate applyAction
        applyAction -> commentField : comment=getText()
        applyAction -> ctrl : setComment(cell, comment)
        deactivate applyAction

        activate ctrl
        ctrl -> cell : addUserComment(comment)
        create u
        cell -> u : create()
        ctrl -> uic : setWorkbookModified(...)
        deactivate ctrl
    end
@enduml