@startuml core02_01_design3.png
    participant "uiExtension : UIExtensionComments" as UIExt
    participant "CommentsWithUserUI : JPanel" as cp
    participant "AddCommentWithUserController" as ctrl
    participant "CommentableCellWithMultipleUsers" as cell
    participant "User" as u
    
    create cp
    UIExt -> cp :  create(uic) 

    create ctrl
    cp -> ctrl : create(uic, cp)


    == meanwhile a cell is selected...the user enters text in "commentField" and the textbox loses the focus ==

    alt user changes a comment
        cp -> ctrl : commentsAuthor = changeComment(cell, oldComment, newComment)

        activate ctrl
        create u
        ctrl -> u : create()
        ctrl -> cell : commentsAuthor = changeUserComment(oldComment, newComment, user)
        deactivate ctrl
    else user adds a comment
        cp -> ctrl : commentsAuthor = addComment(cell, comment)
        activate ctrl
        create u
        ctrl -> u : create()
        ctrl -> cell : commentsAuthor = addUserComment(comment, user)
        deactivate ctrl
    end
@enduml