@startuml core02_01_design2.png
    participant "uic: UIController" as uic
    participant "uiExtension : UIExtensionComments" as UIExt
    participant "CommentPanel : JPanel" as cp
    participant "AddCommentWithUserController" as ctrl
    participant "event: SelectionEvent" as event
    participant "cell: Cell" as cell
    participant "activeCell: CommentableCellWithMultipleUsers" as activeCell

    create cp
    UIExt -> cp :  create(uic) 
    
    create ctrl
    cp -> ctrl: create(uic, cp)   
    cp -> uic : addSelectionListener(this)

    note right of uic
        The user selects a cell...
    end note

    uic -> cp : selectionChanged(SelectionEvent event)
    cp -> event : cell=getCell()
    cp -> cell : activeCell=getExtension(CommentsExtension.NAME)

    cp -> ctrl : commentsList = cellSelected(cell);
    ctrl -> activeCell : commentsList = cell.getComments()
    cp -> cp : changeCommentsTest(commentsList)

    note right of cp
        ... the CommentPanel displays the comments of the current cell.
    end note

@enduml