@startuml 

    actor User 
    participant "GlobalSearchSideBar" as UI
    participant "CellInfoDTO" as dto
    participant "ConfigPane" as UIC
    participant "f : Filter" as ft
    participant "UIController" as UIctrl
    participant "GlobalSearchCtrl : ctrl" as ctrl
    participant "Spreadsheet" as sheet
    participant "Cell" as cll
    participant "RegexUtilExtended" as util
    participant "SearchPublisher" <<Singleton>>
    

    User -> UI : Press filters button
    UI -> UIC : open(ctrl)
    UIC -> ctrl: List<Value.types> types=getTypes()
    User <-- UIC : Show the available cell types
    User -> UIC : Selects the cell types to include in the search
    UIC -> ctrl: insertTypes(List<Value.Type> types)
    loop
    User <-- UIC : Ask for the formula to include in the search
    User -> UIC : Insert the formula
    UIC->ctrl: Formula formula = validateFormula(String formula) 
    UIC -> ctrl: insertFormula(formula)
    end
    User <-- UIC : Ask if the comments are to be included
    User -> UIC : Activate comments in the search
    UIC->ctrl : activateComments()
    User -> UI : Inserts regular expression
    UI -> ctrl : checkIfValid(String regex)
    create ft
    ctrl-->ft: create(formulas,types,true)
    ctrl -> UIctrl : Stack<Workbook> stackWorkbooks : getActiveWorkbooks()
    create util 
    ctrl -> util: create(f,stackWorkbooks)
    ctrl -> util : isRegexValid(regex)
    ctrl -> util : setRegex(regex)
    ctrl -> util : searchInWorkbooks()
    loop for Workbooks b :  stackWorkbooks
    loop for Spreadsheet s : listSpreadsheets
    loop for Cells c : listCells
    util -> cll : getValue()
    alt : if comments activated
    util -> util : checkValidFilters(c);
    util -> util : checkIfMatches(String cellContent)
    util -> util : checkIfCommentMatches(String commentContent)
    else : case comments are desactivated
    util -> util : checkIfMatches(String cellContent)
    end
    alt : if true
    create dto
    util  -> dto : create(c,spreadsheetNumber,b,workbookName())
    util-> SearchPublisher : notifyObservers(dto)
    end
    end
    end
    end
    UI -> UI : update()
    UI-->User: Show search results

    
@enduml
