@startuml
class GlobalSearchSideBar {
    showInfo()
}
class ConfigPane {
    showInfo()
}
class UIController{
    getActiveWorkbooks()
}
class GlobalSearchController{
    validateFormula(String formula)
    start(Filter filter,String regex)
    stop()
}
class Cell{
    getValue()
    getContent()
}
class RegexUtilExtended {
    searchWorkbooks()
    checkIfMatches(Cell cell)
    containsFormulas(Cell cell, List<String> formulas)
    validateFilters(Cell cell, List<String> types, List<String> formulas)
    validateType(Cell cell, List<String> types)
    validateFormulas(Cell cell, List<String> formulas)

}
class Filter{
    getTypesToInclude()
    getFormulasToInclude()
    isIncludeComments()
}
GlobalSearchSideBar ..>ConfigPane
ConfigPane..>UIController
ConfigPane..>GlobalSearchController
GlobalSearchSideBar ..> UIController
GlobalSearchSideBar ..> GlobalSearchController
GlobalSearchController ..> RegexUtilExtended
GlobalSearchController ..> Filter
RegexUtilExtended ..> Cell
@enduml