@startuml lang02_2_sd.png

actor User
participant "UI"
participant "FormulaEvalVisitor" as FEV
participant "ExcelExpressionCompiler" as Compiler
participant "globalVar :Variable" as Var
participant "ExpressionVisitor"
participant "Operation"
participant "UIController" as ctrl
participant "Workbook" as work
participant "VarContentor" as Contentor

title \nLang02.2 - Global Variables - Sequence Diagram\n\n

activate UI
User -> UI : Introduces formula containing global variable(s)
UI -> FEV : visitExpression (expression)
deactivate UI
activate FEV
activate Compiler
FEV -> Compiler : getStarter()
FEV -> Compiler : compile(cell,source)
deactivate Compiler

create Var
FEV --> Var : create(name, expression)

activate ctrl
FEV -> ctrl : activeWorkbook()
deactivate ctrl
activate work
FEV -> work: updateGlobalVariable(globalVar)
activate Contentor
work -> Contentor : update(globalVar)
deactivate Contentor
deactivate work

activate Compiler
FEV -> Compiler : visitGlobalVariable(globalVar)
create ExpressionVisitor
Compiler->ExpressionVisitor : create
deactivate Compiler
activate ExpressionVisitor
activate Operation
ExpressionVisitor -> Operation : evaluate()
ExpressionVisitor -> Operation : accept(ExpressionVisitor visitor)
Operation --> Operator : applyTo()
deactivate Operation
deactivate ExpressionVisitor
activate UI
FEV -> UI
deactivate FEV
UI -> User : Displays the formula result
@enduml