@startuml lang02.1_cd.png


title \nLang02.2 - Global Variables - Class Diagram\n\n

class Variable{
 - name :String
 - expression : Expression
}

interface Serializable{
}

class ExcelExpressionCompiler{
    +char getStarter()
    +Expression compile(Cell cell, String source)
}

class VarContentor{
    +void update()
}

class Formula {
	+Formula(Cell cell, Expression expression) 
}
interface Expression {
	+Value evaluate()
	+Object accept(ExpressionVisitor visitor)
}

interface Operator {
}

class Operator {
    + applyTo()
}

abstract class Operation <O extends Operator> {
    + getOperator() 
}

interface FormulaEvalVisitor {
        +Expression visitExpression(Expression expression)
	+Object visitGlobalVariable (Variable globalVar)
}

Expression <|-- Formula
Expression <|-- Variable

Operation <|-- UnaryOperation
Operation <|-- BinaryOperation
Operation <|-- NaryOperation

UnaryOperation --> Expression : operand
BinaryOperation --> Expression : leftOperand
BinaryOperation --> Expression : rightOperand
NaryOperation --> Expression : operands

Operator <|-- UnaryOperator
Operator <|-- BinaryOperator
Operator <|-- NaryOperator

Operation <-- Operator

FormulaEvalVisitor ..> VarContentor
VarContentor *-- Variable
Variable --|> Serializable
VarContentor --|> Serializable
  @enduml