@startuml core02_03_design2.png

    participant "CommentsWithHistoryUI" as ui
    participant "CommentsWithHistoryController" as ctrl
    
    create ctrl
    ui -> ctrl : create(uic)

    ui -> ctrl : selectComment()
    activate ctrl
    ui <-- ctrl : showHistory()
    deactivate ctrl

@enduml