@startuml start_sharing.png

'http://plantuml.com/skinparam.html'
skinparam handwritten true
skinparam defaultFontName FG Virgil
skinparam shadowing false

participant CellDTO
participant "dto : CellDTO" as dto
participant "aCell : Cell" as aCell
participant "styleableCell : StylableCell" as sCell
participant Styles

-> CellDTO : createFromCell(aCell)

create dto
CellDTO -> dto : create(aCell.address, aCell.content)
CellDTO -> aCell : styleableCell = getExtension(StyleExtension.NAME)

alt styleableCell != null
CellDTO -> Styles : styleDTO = createStyleDtoFromCell(styleableCell)
note right
    util class to retrieve information
    from the cell and create a StyleDTO
    with that information
end note
CellDTO -> dto : setStyleDTO(styleDTO)
<- CellDTO : return dto



@enduml