@startuml us06.1_analysis_classes.png

interface DataTransmissionContext {
    inputStream(InputStream socketInStream) : ObjectInputStream
    outputStream(OutputStream socketOutStream) : ObjectOutputStream
}

class BasicDataTransmissionContext
class SecuredTransmissionContext {
    cipher: Cipher
}

DataTransmissionContext <|-- BasicDataTransmissionContext
DataTransmissionContext <|-- SecuredTransmissionContext


@enduml