@startuml us06.1_design_bdtc.png

title Basic Unsecured Connection

participant BasicDataTransmissionContext

-> BasicDataTransmissionContext : inputStream(sis:InputStream ) : ObjectInputStream
create "o: ObjectInputStream" as ObjectInputStream
    BasicDataTransmissionContext -> ObjectInputStream :new ObjectInputStream(sis)
<-- BasicDataTransmissionContext: return o
||100||
-> BasicDataTransmissionContext : outputStream(sos:OutputStream ) : ObjectOutputStream
create "o: ObjectOutputStream" as ObjectOutputStream
    BasicDataTransmissionContext -> ObjectOutputStream :new ObjectOutputStream(sos)
<-- BasicDataTransmissionContext: return o

@enduml