@startuml
actor User
User -> ExportXMLUI : Initiates Functionality
ExportXMLUI->ExportXMLController: initiateExport()
create ExportXML
ExportXMLController->ExportXML : create
create ExportContext
ExportXMLController->ExportContext : create(exportXML)
User -> ExportXMLUI : Selects Range
ExportXMLUI->ExportXMLController: selectRange(r)
ExportXMLController->ExportXML: selectRange(r)
User -> ExportXMLUI : Chooses the tag names
ExportXMLUI->ExportXMLController: configureTagNames()
ExportXMLController->ExportXML: configureTagNames()
User -> ExportXMLUI : Chooses the path where to save
ExportXMLUI->ExportXMLController: selectPath(path)
ExportXMLController->ExportXML: selectPath(path)

User -> ExportXMLUI : Confirms data
ExportXMLUI -> ExportXMLController : export()

ExportXMLController -> ExportContext : executeStrategy()
@enduml