@startuml cd_notes_edition.png
skinparam handwritten true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false 
skinparam SequenceMessageAlign center

class NotesEditionUI{    
}
class NotesEditionController{
    +getContacts()
    +notesOfContact(Contact c)
    +notesContentOfNote(n)
    +addNote(String title, String content) 
    +editNote(Note n, String content)
    +removeNote(Note n)
}
class ContactRepository{
    +contacts()
}
class Contact{
}
class NoteList{
    +List : getNoteList()
    +boolean : add(title, content)
    +boolean : edit(title, content)
    +boolean : remove(title)
}
class Note{
    -String : title
    -boolean : removed
    +List : getNoteContentList()
    +boolean : add(content)
    +boolean : remove()
    +boolean : isRemoved()
}
class "NoteContent\n<<value object>>"{
    -Calendar : timestamp
    -String : contentNode
}

NotesEditionUI .> NotesEditionController
NotesEditionController .-> ContactRepository
NotesEditionController .-> NoteList
NotesEditionController .-> Contact
ContactRepository -> Contact : save
Contact *-> NoteList
NoteList *-> Note
Note *-> "NoteContent\n<<value object>>"

@enduml
