@startuml
actor User
User -> System: Selects Workbook Search
System --> User: Asks for the regular expression to search


User -> System: Inserts the regular expression
User <-- System: Displays search results

@enduml