@startuml 

    actor User 
    participant "UIExtensionSearch" as UI
    participant "UIController" as UIctrl
    participant "WorkbookSearchCtrl" as ctrl
    participant "Workbook" as WBOOK
    participant "Spreadsheet" as sheet
    participant "Cell" as cll
    participant "RegexUtil" as util

    User -> UI : begin
    activate UI 
    UI -> UIctrl : Workbook w : getActiveWorkbook()
    User <-- UI : asks for regular expression
    deactivate ctrl
    deactivate UI
    User -> UI : Inserts regular expression
    activate UI
    UI -> ctrl : checkIfValid(String regex)
    activate ctrl
   
    ctrl -> util : isRegexValid(regex)
    activate util
 deactivate ctrl
    deactivate util

    UI -> ctrl : searchWorkbook(String regex)
    activate ctrl
    ctrl -> util : searchInWorkbook(w)
    activate util
    
    loop for Spreadsheet s : listSpreadsheets
    loop for Cells c : listCells
    util -> cll : getContent()
    util -> util : checkIfMatches(String cellContent)
   
    alt : if true
    util -> util : searchResults.add()
    end
    end
    end
    util -> ctrl : return searchResults
    deactivate util
    UI <-- ctrl : return searchResults
    UI -> UI : showInfo()
    deactivate ctrl
    
@enduml
