@startuml us025_design_sd.png

actor User
participant ExportPDFUI as UI
participant ExportStylePDFController as Controller


User -> UI : Initiates functionality and \nconfigures the export functionality
activate UI
create Controller
UI -> Controller : new(configurations)
note right
    Export configurations include: 
        - The range of cells to be exported;
        - The path of the file;
        - The existence of sections;
        - The border line and color.
end note

UI -> Controller : manageConfigurations()
activate Controller
create ExportPDF
Controller -> ExportPDF : new()
create ExportContext
Controller -> ExportContext : new(exportPDF)
User <-- UI : Requests confirmation
deactivate Controller
deactivate UI

note right of User
    The use of the WorkbookHandler to get the styled data to be exported will be explained in another diagram in order to simplify this diagram
end note

User -> UI : Confirms
activate UI
UI -> Controller : export()
note right of UI
    It was used a thread 
    for the execution
    of this method
end note
activate Controller
Controller -> ExportContext : executeStrategy()
activate ExportContext
ExportContext -> ExportPDF : export()
deactivate ExportContext
activate ExportPDF
UI <-- Controller : Success
deactivate ExportPDF
deactivate Controller
User <-- UI : Success
deactivate UI

@enduml us025_design_sd.png
