@startuml core02_01_design3.png
    participant "MoneyLanguageVisitor" as som
    participant "ConfigureExchangeRatesController" as ctrl
    participant "MonetaryConvertion" as mon
    

    [-> som: create()
    som -> ctrl : exchangeRates = getExchangeRates()

    
    == meanwhile the tree is visited ==
    
    
    create mon
    som -> mon : create()
    som -> mon : convertTo(amount, value)
@enduml