@startuml core02_03_design1.png

    participant "User" as user
    participant "CommentsWithHistoryUI" as ui
    participant "ComplexCellRenderer" as renderer
    
    user -> ui : Enters format
    activate ui

    ui -> renderer
    activate renderer
    renderer -> renderer : getListCellRendererComponent()
    ui <-- renderer
    deactivate renderer

    user <-- ui : Comment formatted
    deactivate ui

    user -> ui : Enters style
    activate ui

    ui -> renderer
    activate renderer
    renderer -> renderer : getListCellRendererComponent()
    ui <-- renderer
    deactivate renderer
    user <-- ui : Comment styled
    deactivate ui

@enduml