@startuml traffic_log_flow.png

(*) --> "TrafficInputStream" as in
in --> [run()] "incoming1" as i1
in --> [run()] "incoming2" as i2

(*) --> "TrafficOutputStream" as out
out --> [run()] "outgoing1" as o1
out --> [run()] "outgoing2" as o2

i1 --> [add()] "TrafficLogger" as tl
i2 --> [add()] tl
o1 --> [add()] tl
o2 --> [add()] tl
note left: sync events.add()
if events empty? then
--> [No] "TrafficLoggerUI" as ui
ui --> [update list] ui
else
-> [Yes] "wait"
--> [read event] tl

@enduml
