  @startuml us02.1_analysis.png


  create SearchWorkbookUI
  SearchWorkbookUI -> SearchController : insert the path to search
  SearchWorkbookUI <-- SearchController : piroca
    
  create SearchController
  SearchController -> Directory : new();
    
 

  @enduml