package lapr4.red.s1.core.n1150623.labelsForContacts.presentation;

import lapr4.red.s1.core.n1150623.labelsForContacts.application.LabelsForContactsController;
import lapr4.white.s1.core.n4567890.contacts.domain.Contact;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Guilherme Ferreira 1150623
 */
public class LabelsForContactsUI extends javax.swing.JFrame {

    private DefaultListModel<Contact> selected;
    private DefaultListModel<Contact> contacts;
    private LabelsForContactsController controller;

    /**
     * Creates new form FilterUI
     *
     * @param controller
     */
    public LabelsForContactsUI(LabelsForContactsController controller) {
        selected = new DefaultListModel<>();
        contacts = new DefaultListModel<>();
        Iterable<Contact> it = controller.allContacts();
        for (Contact c : it) {
            contacts.addElement(c);
        }
        initComponents();
        setup();
        this.controller = controller;
    }

    private void setup() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        addAllContactsButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        applyRegexButton = new javax.swing.JButton();
        regexExpressionField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedContactsList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contactList.setModel(contacts);
        jScrollPane1.setViewportView(contactList);

        jLabel1.setText("Choose your contacts to export:");

        addAllContactsButton.setText("Add All");
        addAllContactsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllContactsButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Add Selected");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        applyRegexButton.setText("Apply Filter");
        applyRegexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyRegexButtonActionPerformed(evt);
            }
        });

        regexExpressionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regexExpressionFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(applyRegexButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regexExpressionField))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addAllContactsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(addAllContactsButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regexExpressionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyRegexButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


        regexExpressionField.setColumns(25);

        jButton6.setText("Remove Selected");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        selectedContactsList.setModel(selected);
        jScrollPane2.setViewportView(selectedContactsList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCancel)
                .addGap(18, 18, 18)
                .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOK)
                    .addComponent(buttonCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAllContactsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllContactsButtonActionPerformed
        addAllContacts();
    }//GEN-LAST:event_addAllContactsButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addSelected();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        onOK();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        removeSelected();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void applyRegexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyRegexButtonActionPerformed
        applyRegex();
    }//GEN-LAST:event_applyRegexButtonActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        onCancel();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void regexExpressionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regexExpressionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regexExpressionFieldActionPerformed

    private void addSelected() {
        List<Contact> list = new ArrayList<>();
        list = contactList.getSelectedValuesList();

        addToSelectedContacts(list);
        removeFromContacts(list);

        updateAllContactsList();
        updateSelectedContactsList();
    }

    private void removeSelected() {
        List<Contact> toRemove = selectedContactsList.getSelectedValuesList();
        addToContacts(toRemove);
        removeFromSelectedContacts(toRemove);
        updateAllContactsList();
        updateSelectedContactsList();
    }

    private void applyRegex() {
        String regex = regexExpressionField.getText().trim();
        if (regex.length() > 0) {
            List<Contact> fullList = new ArrayList<>();
            Iterable<Contact> it = controller.allContacts();

            for(Contact c: it){
                if(!selected.contains(c)) {
                    fullList.add(c);
                }
            }

            List<Contact> foundContacts = new ArrayList<>();
            Pattern p = Pattern.compile(regex);
            Contact c = null;
            for (int i = 0; i < fullList.size(); i++) {
                c = fullList.get(i);
                Matcher m = p.matcher(c.name());
                if (m.matches()) {
                    foundContacts.add(c);
                }
            }
            contacts.removeAllElements();
            addToContacts(foundContacts);
            updateAllContactsList();
        } else {
            //Filter is removed
            List<Contact> fullList = new ArrayList<>();
            Iterable<Contact> it = controller.allContacts();

            for(Contact c: it){
                if(!selected.contains(c)) {
                    fullList.add(c);
                }
            }

            contacts.removeAllElements();
            addToContacts(fullList);
        }
    }

    private void onOK() {

        if (selected.size() > 0) {
            Contact c = null;
            for (int i = 0; i < selected.size(); i++) {
                c = selected.getElementAt(i);
                    if (c != null) {
                        controller.addLabel(c.name(), c.photo(), c.email(), c.address(), c.phone(), c.agenda());
                    }
            }

            ExportDetailsController ctrl = new ExportDetailsController(controller, this);
            
            if (JOptionPane.showConfirmDialog(null, "Export Events?", "Label Exportation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                ctrl.runDateChooser();

            } else {
                ctrl.runPathChooser();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Must select at least one contact", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onCancel() {
        dispose(); //nothing more to do...
    }

    private void updateAllContactsList() {
        contactList.setModel(contacts);
    }

    private void updateSelectedContactsList() {
        selectedContactsList.setModel(selected);
    }

    private void removeFromContacts(List<Contact> toRemove) {
        toRemove.stream().forEach((c) -> {
            contacts.removeElement(c);
        });
        updateAllContactsList();
        updateSelectedContactsList();
    }

    private void addToContacts(List<Contact> toAdd) {
        toAdd.stream().forEach((c) -> {
            contacts.addElement(c);
        });
        updateAllContactsList();
        updateSelectedContactsList();
    }

    private void addAllContacts() {
        Contact c = null;
        for (int i = 0; i < contacts.size(); i++) {
            c = contacts.getElementAt(i);
            selected.addElement(c);
        }
        contacts.removeAllElements();
        updateAllContactsList();
        updateSelectedContactsList();
    }

    private void addToSelectedContacts(List<Contact> toAdd) {
        toAdd.stream().forEach((c) -> {
            selected.addElement(c);
        });
        updateAllContactsList();
        updateSelectedContactsList();
    }

    private void removeFromSelectedContacts(List<Contact> toRemove) {
        toRemove.stream().forEach((c) -> {
            selected.removeElement(c);
        });
        updateAllContactsList();
        updateSelectedContactsList();
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton addAllContactsButton;
    private javax.swing.JButton applyRegexButton;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JList<Contact> contactList;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField regexExpressionField;
    private javax.swing.JList<Contact> selectedContactsList;
}
