@startuml ipc03_2_design1.png
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User 
participant "NetworkSearchPanel" as panel
participant "NetworkSearchAction" as action
participant "SearchWorkbookRequestDTO" as reqDTO
participant "CommUDPClient" as udpClient
participant "HandlerSearchWorkbookResponseDTO" as handlerResponse

User -> panel : inserts the name of the workbook
panel -> action : create(resultsTable, portNumber, workbookName)
create reqDTO
action -> reqDTO : searchRequest = create(String namePattern,String contentPattern)
create udpClient
action -> udpClient : create(searchRequest, portNumber, timeout)
create handlerResponse
action -> handlerResponse : create()
handlerResponse -> handlerResponse : addObserver(resultsTable)
reqDTO -> reqDTO : addHandler(SearchWorkbookResponseDTO)
udpClient -> udpClient : start()
@enduml
@enduml
