@startuml ipc03_2_design3.png
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

participant "HandlerSearchWorkbookRequestDTO" as handlerDTO
participant "PacketEncapsulatorDTO" as packet
participant "UIController" as uiController
participant "SearchWorkbookResponseDTO" as resDTO
participant "SearchResults" as sresults
participant "File" as file
participant "ObjectOutputStream" as oos

-> handlerDTO : handleDTO(dto)
handlerDTO -> packet : request = getDTO()
handlerDTO -> packet : String workbookName = getWorkbookName()
handlerDTO -> uiController : Stack<Workbook> activeWorkbooks = getActiveWorkbooks()
loop forEach Workbook workbook : activeWorkbooks
handlerDTO -> uiController : String name = getFile(workbook)
uiController -> file : getName()
loop forEach Spreadsheet spreadsheet : workbook.getSpreadsheets()
handlerDTO -> handlerDTO : spreadsheetList.add(spreadsheet)
end
create sresults
handlerDTO -> sresults : create()
handlerDTO -> handlerDTO : resultList.add(searchResult)
end
create resDTO
handlerDTO -> resDTO : reply = create()
handlerDTO -> oos : writeObject(reply)

@enduml
