@startuml ipc03_2_design2.png
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

participant "HandlerSearchWorkbookRespoonseDTO" as handlerDTO
participant "PacketEncapsulatorDTO" as packet
participant "DatagramPacket" as datagram
participant "SearchWorkbookResponseDTO" as resDTO
participant "SearchResults" as sresult
participant "Observable" as obs

-> handlerDTO : handleDTO()
handlerDTO -> packet : reply = (PacketEncapsulator) dto
handlerDTO -> packet : InetAddress ip = getPacket()
packet -> datagram : getAddress()
handlerDTO -> packet : List<SearchResults> results = getDTO()
packet -> resDTO : getSearchResultsList
loop forEach result : results
handlerDTO -> sresult : setAddress(ip)
handlerDTO -> obs : notifyObservers(result)
end

@enduml
