@startuml receive_cell_content_sd.png

'http://plantuml.com/skinparam.html'
skinparam handwritten true
skinparam defaultFontName FG Virgil
skinparam shadowing false


participant "ShareContentCellListener" as listener << Listener >>
participant "ctrl : SharingAutomaicUpdateController" as ctrl << Controller >>
participant "CommTCPClientsManager" as tcpCliMan << Singleton >>
participant "CellContentDTO" as dto << DTO >>
participant "worker : CommTCPClientsManager" as worker << Thread >>


note over listener
    Cells are being shared
end note

note over listener
    The value of a cell is changed
    and the ShareContentCellListener
    is notified
end note

activate listener
listener -> ctrl : shareCellContent(cell)
activate ctrl

ctrl -> tcpCliMan : shareCellContent(connection, cell)
activate tcpCliMan

tcpCliMan -> tcpCliMan : worker = clients.get(connection)
tcpCliMan -> dto : dto = createFromCell(cell)
activate dto
deactivate dto

tcpCliMan -> worker : getObjectOutputStream().writeObject(dto);
activate worker
deactivate worker

deactivate tcpCliMan
deactivate ctrl
deactivate listener

@enduml