@startuml ref1.png
participant "ConditionalStyleController" as ctrl
participant "iteratedCell: ConditionStylableCell" as cell
participant "adrs : Address" as address
participant "cellAddress : String" as adrs
participant "condition : String" as cond


    ctrl -> cell : adrs = getAddress()
    ctrl -> address : cellAddress = toString()
    -> ctrl : verifyCondition(condition, cellAddress)
    ctrl -> cond : replaceAll("_cell",cell)
@enduml