@startuml us10.1.2_concept_classes.png

skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

hide methods
class CompanyName <<value object>>
class Profession <<value object>>
class CompanyContact <<aggregate root>> <<CompanyName>>
class Image  <<value object>>
interface Contact
class PersonContact <<aggregate root>> {
    firstName
    lastName
    photo
}

class Agenda {
}

class Event {
    description
    dueDate
}

Contact <.. CompanyContact
Contact <.. PersonContact
CompanyContact -> CompanyName
CompanyContact --> Image
CompanyName <-  PersonContact
PersonContact *--> Profession
PersonContact *--> "1" Agenda
Agenda *--> "*" Event


@enduml