@startuml lang03_1_analysis_basic_sd.png
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

  actor User 
  participant "<<analysis>>\nConditionStyleUI" as UI
  participant "<<analysis>>\nConditionStyleCtrl" as ctrl
  participant "<<analysis>>\nSpreadsheet" as sheet
  participant "<<analysis>>\nCell" as cell
  User -> UI : selectCell()
  activate UI 
  UI -> ctrl : getCellCondition()
  activate ctrl
  ctrl -> sheet : getCell()
  ctrl -> cell : getCellCondition()
  ctrl -> ctrl : boolean = toBoolean()
  deactivate ctrl
  UI -> UI : applyStyle()
  deactivate UI
  @enduml
