@startuml uc_create_event.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

title Use Case: Add Event

actor "CRM User" as Actor  
participant AddEventUI as UI <<presentation>>
participant AddEventController as Controller <<application>>
participant "event:Event" as Domain <<domain>>
database EventRepository as Repository <<repository>>

Actor --> UI: Selects one contact in his list
Actor --> UI: Add Event
activate UI
    UI -> Controller: create
    Actor --> UI: Due Date,\nDescription
    UI -> Controller: addEvent(dueDate, description)
    activate Controller
        Controller -> Domain: create(dueDate, description)
        activate Domain
            Domain -> Domain: validate
            Domain -> Controller: event
        deactivate Domain
        Controller -> Repository: save(event)
        Controller -> UI: event
    deactivate Controller
    UI --> Actor: Display Event Info
deactivate UI

@enduml