@startuml
class UIExtensionSearch{
    showInfo()
}
class UIController{
    getActiveWorkbook()
}
class WorkbookSearchCtrl{
    checkIfValid()
    searchInWorkbook()
}
class Cell{
    getValue()
}
class RegexUtil {
    checkIfMatches()
    isRegexValid()
    searchInWorkbook()
}

UIExtensionSearch ..> UIController
UIExtensionSearch ..> WorkbookSearchCtrl
WorkbookSearchCtrl ..> Cell
WorkbookSearchCtrl ..> RegexUtil
@enduml