@startuml
actor User
User -> System: Press filters button
User <-- System: Show the available cell types
User -> System: Selects the cell types to include in the search
User <-- System: Ask for the formulas to include in the search
User -> System: Insert the formulas
User <-- System: Asks for the regular expression to search
User -> System: Inserts the regular expression
User <-- System: Displays search results
@enduml