@startuml ipc04_02_design_export.png

participant "ExportDataUI" as UI
participant "FileChooser" as FileChooser
participant "ExportDataController" as Controller
participant "UIController" as UIController
participant "Spreadsheet" as Spreadsheet
participant "CellDTO" as CellDTO
participant "LinkTxtExportController" as Controller
participant "WriterThread" as Thread

activate UI
UI -> FileChooser : new()
activate FileChooser
UI <-- FileChooser : Requests file
UI -> FileChooser : getFileToSave()
UI <-- FileChooser : file
deactivate FileChooser
create Controller
UI -> Controller : new(file)
activate Controller
Controller -> UIController : getActiveSpreadsheet()
loop for (cell in range)
    create CellDTO
    Controller -> CellDTO : createFromCell(cell)
end
Controller -> Controller : setFileData(cellList)
Controller -> LinkTxtExportController : new()
activate LinkTxtExportController
Controller -> LinkTxtExportController : fireLinkWriterThread()
LinkTxtExportController -> WriterThread : new()
activate WriterThread
WriterThread -> WriterThread : start()
UI <-- Controller : success
deactivate Controller
deactivate UI

@enduml ipc04_02_design_export.png
