@startuml

box "SSD"
    participant "Client"
    participant "Cleansheets"
end box

    Client -> Cleansheets : Chooses to search workbook.
    Cleansheets -> Client : Requests the name of the workbook.
    Client -> Cleansheets : Introduces the name.
    Cleansheets -> Client : Searches the workbook and informs if it was found or not. If it was found, presents a summary of it's contents.

@enduml
